---
server:
  port: 8001
  servlet:
    context-path: /rest

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
      instance:
        prefereIpAddress: true

spring:
  data:
    mongodb:
      host: ${AUTH_DB_PORT:localhost}
      port: ${AUTH_DB_PORT:27017} # default

auth:
  jwt:
    expiry: 30 # minutes
    key:
      private: ${KBE_JWT_PRIVATE_KEY} # rsa-key
