---
server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
      instance:
        prefereIpAddress: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: songs
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/rest/songs/**, /rest/playlists/**, /rest/playlists/share/**
          filters:
            - RewritePath=/songs/(?<path>.*), /$\{path}
        - id: playlists
          uri: lb://PLAYLIST-SERVICE
          predicates:
            - Path=/rest/playlists/**
          filters:
            - RewritePath=/playlists/(?<path>.*), /$\{path}
        - id: users
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/rest/users/**
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}
        - id: auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/rest/auth/**
          filters:
            - RewritePath=(?<path>.*), /$\{path}
