---
server:
  port: ${PORT:8008}
  servlet:
    context-path: /rest
spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
  datasource:
    driver-class-name: org.postgresql.Driver
  username: wcwdeychpkninf
  password: fc60feeaedadd970b36a845c4a00a009c304baee82aa8215ac2d9d6038ee4207
  url: jdbc:postgresql://ec2-54-228-250-82.eu-west-1.compute.amazonaws.com:5432/d9dqj7qrho0d4d
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: true
    hibernate.ddl-auto: update
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      prefereIpAddress: true
auth:
  jwt:
    key:
      public: ${KBE_JWT_PUBLIC_KEY}
